"""Qt dialog for creating a custom AI-generated desktop character.

The character can be generated by OpenAI (hosted) or by a self-hosted Stable
Diffusion (AUTOMATIC1111) or ComfyUI server. Each backend offers txt2img (prompt
only) and img2img (uses the reference photos), and the self-hosted ones can list
their checkpoints so you can pick a model. All settings persist in config.ini.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from PySide6 import QtCore, QtGui, QtWidgets

from . import ai_backends, ai_char, char_catalog, secret_store
from .ui_theme import LIGHT_QSS

logger = logging.getLogger(__name__)

BACKEND_LABELS = [
    ("OpenAI (hosted, transparent)", "openai"),
    ("Stable Diffusion — self-hosted", "a1111"),
    ("ComfyUI — self-hosted", "comfyui"),
]
MODE_LABELS = [
    ("img2img — turn my photos into a cat", "img2img"),
    ("txt2img — from the prompt only", "txt2img"),
]


class GenerationSignals(QtCore.QObject):
    completed = QtCore.Signal(str, str)
    failed = QtCore.Signal(str)


class GenerationWorker(QtCore.QRunnable):
    def __init__(self, name: str, paths: list[Path], settings: dict, api_key: str) -> None:
        super().__init__()
        self.name = name
        self.paths = paths
        self.settings = settings
        self.api_key = api_key
        self.signals = GenerationSignals()

    def run(self) -> None:
        kind = self.settings.get("backend", "openai")
        mode = self.settings.get("mode", "img2img")
        logger.info("Generating a character (backend=%s, mode=%s)", kind, mode)
        try:
            references = ai_char.prepare_references(self.paths) if self.paths else []
            backend = ai_backends.make_backend(self.settings, self.api_key)
            image = backend.generate(references)
            char_id, path = ai_char.install_character(self.name, image)
        except Exception as exc:  # noqa: BLE001 - error is shown in the dialog
            logger.warning("Character generation failed (backend=%s, mode=%s): %s", kind, mode, exc)
            self.signals.failed.emit(str(exc))
        else:
            logger.info("Character generation succeeded: %s", char_id)
            self.signals.completed.emit(char_id, str(path))


class ModelSignals(QtCore.QObject):
    loaded = QtCore.Signal(list)
    failed = QtCore.Signal(str)


class ModelLoadWorker(QtCore.QRunnable):
    def __init__(self, kind: str, url: str) -> None:
        super().__init__()
        self.kind = kind
        self.url = url
        self.signals = ModelSignals()

    def run(self) -> None:
        try:
            models = ai_backends.list_models(self.kind, self.url)
        except Exception as exc:  # noqa: BLE001 - shown in the dialog
            self.signals.failed.emit(str(exc))
        else:
            self.signals.loaded.emit(models)


class AICharDialog(QtWidgets.QDialog):
    character_created = QtCore.Signal(str)

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Generate a custom cat with AI")
        self.setMinimumWidth(540)
        self.setStyleSheet(LIGHT_QSS)
        self.pool = QtCore.QThreadPool(self)
        self.reference_paths: list[Path] = []
        self.settings = ai_backends.load_generation_settings()
        self.current_kind = self.settings.get("backend", "openai")

        intro = QtWidgets.QLabel(
            "Turn 1–3 photos of the same person into a cute chibi cat, or generate one "
            "from the prompt. Reference photos are not stored by myCat."
        )
        intro.setWordWrap(True)

        self.name_edit = QtWidgets.QLineEdit()
        self.name_edit.setPlaceholderText("Example: Mina chibi cat")

        self.backend_combo = QtWidgets.QComboBox()
        for label, data in BACKEND_LABELS:
            self.backend_combo.addItem(label, data)
        self.mode_combo = QtWidgets.QComboBox()
        for label, data in MODE_LABELS:
            self.mode_combo.addItem(label, data)

        # --- OpenAI group -----------------------------------------------------
        self.key_edit = QtWidgets.QLineEdit()
        self.key_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        saved_key = secret_store.get_secret(ai_char.SECRET_NAME)
        self.key_edit.setText(saved_key or os.getenv("OPENAI_API_KEY", ""))
        self.key_edit.setPlaceholderText("sk-… (or OPENAI_API_KEY)")
        self.remember_box = QtWidgets.QCheckBox("Remember key in the operating system keyring")
        self.remember_box.setChecked(bool(saved_key))
        self.remember_box.setEnabled(secret_store.keyring_available())
        if not self.remember_box.isEnabled():
            self.remember_box.setToolTip("Install mycat[secure] and configure an OS keyring to enable this.")
        self.model_combo = QtWidgets.QComboBox()
        for model in ai_backends.OPENAI_MODELS:
            self.model_combo.addItem(model, model)
        self.quality_combo = QtWidgets.QComboBox()
        self.quality_combo.addItem("Low — cheaper, good for a mascot", "low")
        self.quality_combo.addItem("Medium — more detail, costs more", "medium")

        openai_form = QtWidgets.QFormLayout()
        openai_form.addRow("OpenAI API key", self.key_edit)
        openai_form.addRow("", self.remember_box)
        openai_form.addRow("Model", self.model_combo)
        openai_form.addRow("Quality", self.quality_combo)
        self.openai_group = QtWidgets.QGroupBox("OpenAI")
        self.openai_group.setLayout(openai_form)

        # --- Self-hosted server group ----------------------------------------
        self.url_edit = QtWidgets.QLineEdit()
        self.url_edit.setPlaceholderText("http://127.0.0.1:7860")
        self.load_btn = QtWidgets.QPushButton("Load models")
        self.load_btn.clicked.connect(self.load_models)
        url_row = QtWidgets.QHBoxLayout()
        url_row.addWidget(self.url_edit, 1)
        url_row.addWidget(self.load_btn)
        self.checkpoint_combo = QtWidgets.QComboBox()
        self.checkpoint_combo.setEditable(True)
        self.steps_spin = QtWidgets.QSpinBox()
        self.steps_spin.setRange(1, 80)
        self.steps_spin.setValue(int(self.settings.get("steps", ai_backends.LOCAL_STEPS)))
        local_form = QtWidgets.QFormLayout()
        local_form.addRow("Server address", url_row)
        local_form.addRow("Checkpoint", self.checkpoint_combo)
        local_form.addRow("Steps", self.steps_spin)
        self.local_group = QtWidgets.QGroupBox("Self-hosted server")
        self.local_group.setLayout(local_form)

        # Editable prompt (per backend style) + negative (self-hosted only).
        self.prompt_edit = QtWidgets.QPlainTextEdit()
        self.prompt_edit.setMaximumHeight(90)
        self.negative_label = QtWidgets.QLabel("Negative prompt")
        self.negative_edit = QtWidgets.QPlainTextEdit()
        self.negative_edit.setMaximumHeight(70)
        self.negative_edit.setToolTip(
            "Things to avoid. OpenAI has no negative field, so it's folded into the "
            "prompt as 'the image must not contain: …'."
        )
        self.reset_prompt_btn = QtWidgets.QPushButton("Reset to default")
        self.reset_prompt_btn.clicked.connect(self.reset_prompts)

        self.reference_list = QtWidgets.QListWidget()
        self.reference_list.setIconSize(QtCore.QSize(56, 56))
        self.reference_list.setFixedHeight(110)
        add_btn = QtWidgets.QPushButton("Add photos…")
        remove_btn = QtWidgets.QPushButton("Remove selected")
        add_btn.clicked.connect(self.add_references)
        remove_btn.clicked.connect(self.remove_selected)
        photo_buttons = QtWidgets.QHBoxLayout()
        photo_buttons.addWidget(add_btn)
        photo_buttons.addWidget(remove_btn)
        photo_buttons.addStretch(1)

        top_form = QtWidgets.QFormLayout()
        top_form.addRow("Character name", self.name_edit)
        top_form.addRow("Generate with", self.backend_combo)
        top_form.addRow("Mode", self.mode_combo)

        self.status_label = QtWidgets.QLabel("")
        self.status_label.setWordWrap(True)
        self.generate_btn = QtWidgets.QPushButton("Generate")
        close_btn = QtWidgets.QPushButton("Close")
        self.generate_btn.clicked.connect(self.generate)
        close_btn.clicked.connect(self.reject)
        buttons = QtWidgets.QHBoxLayout()
        buttons.addWidget(self.reset_prompt_btn)
        buttons.addStretch(1)
        buttons.addWidget(self.generate_btn)
        buttons.addWidget(close_btn)

        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(intro)
        layout.addLayout(top_form)
        layout.addWidget(self.openai_group)
        layout.addWidget(self.local_group)
        layout.addWidget(QtWidgets.QLabel("Prompt"))
        layout.addWidget(self.prompt_edit)
        layout.addWidget(self.negative_label)
        layout.addWidget(self.negative_edit)
        layout.addWidget(QtWidgets.QLabel("Reference photos (maximum 3)"))
        layout.addWidget(self.reference_list)
        layout.addLayout(photo_buttons)
        layout.addWidget(self.status_label)
        layout.addStretch(1)
        layout.addLayout(buttons)

        # Fix the height to the tallest (self-hosted) layout up front, so switching
        # backends never resizes the window or clips fields — and no scroll area,
        # which would show the system (not the theme's) background.
        self.combo_select(self.backend_combo, "comfyui")
        self.update_visibility()
        tall = self.sizeHint().height()
        self.apply_settings()
        self.setMinimumHeight(tall)
        self.resize(560, tall)
        self.backend_combo.currentIndexChanged.connect(self.on_backend_changed)

    # --- settings <-> widgets -------------------------------------------------
    def combo_select(self, combo: QtWidgets.QComboBox, data: str) -> None:
        index = combo.findData(data)
        if index >= 0:
            combo.setCurrentIndex(index)

    def apply_settings(self) -> None:
        """Populate the widgets from the loaded settings and toggle groups."""
        self.combo_select(self.backend_combo, self.settings.get("backend", "openai"))
        self.combo_select(self.mode_combo, self.settings.get("mode", "img2img"))
        self.combo_select(self.model_combo, self.settings.get("openai_model", ai_backends.OPENAI_MODELS[0]))
        self.combo_select(self.quality_combo, self.settings.get("quality", "low"))
        self.load_local_fields(self.current_kind)
        self.load_prompt_fields(self.current_kind)
        self.update_visibility()

    def style_of(self, kind: str) -> str:
        """Prompt style key: OpenAI has its own; the self-hosted backends share one."""
        return "openai" if kind == "openai" else "selfhosted"

    def load_prompt_fields(self, kind: str) -> None:
        style = self.style_of(kind)
        self.prompt_edit.setPlainText(self.settings.get(f"{style}_prompt", ""))
        self.negative_edit.setPlainText(self.settings.get(f"{style}_negative", ""))

    def stash_prompt_fields(self, kind: str) -> None:
        style = self.style_of(kind)
        self.settings[f"{style}_prompt"] = self.prompt_edit.toPlainText()
        self.settings[f"{style}_negative"] = self.negative_edit.toPlainText()

    def reset_prompts(self) -> None:
        style = self.style_of(self.backend_combo.currentData())
        self.prompt_edit.setPlainText(ai_backends.GENERATION_DEFAULTS[f"{style}_prompt"])
        self.negative_edit.setPlainText(ai_backends.GENERATION_DEFAULTS[f"{style}_negative"])

    def load_local_fields(self, kind: str) -> None:
        if kind in ("a1111", "comfyui"):
            self.url_edit.setText(self.settings.get(f"{kind}_url", ""))
            checkpoint = self.settings.get(f"{kind}_checkpoint", "")
            self.checkpoint_combo.clear()
            if checkpoint:
                self.checkpoint_combo.addItem(checkpoint)
                self.checkpoint_combo.setCurrentText(checkpoint)

    def stash_local_fields(self, kind: str) -> None:
        if kind in ("a1111", "comfyui"):
            self.settings[f"{kind}_url"] = self.url_edit.text().strip()
            self.settings[f"{kind}_checkpoint"] = self.checkpoint_combo.currentText().strip()

    def on_backend_changed(self) -> None:
        self.stash_local_fields(self.current_kind)
        self.stash_prompt_fields(self.current_kind)
        self.current_kind = self.backend_combo.currentData()
        self.load_local_fields(self.current_kind)
        self.load_prompt_fields(self.current_kind)
        self.update_visibility()

    def update_visibility(self) -> None:
        kind = self.backend_combo.currentData()
        self.openai_group.setVisible(kind == "openai")
        self.local_group.setVisible(kind in ("a1111", "comfyui"))

    def collect_settings(self) -> dict:
        self.stash_local_fields(self.current_kind)
        self.stash_prompt_fields(self.current_kind)
        settings = dict(self.settings)
        settings["backend"] = self.backend_combo.currentData()
        settings["mode"] = self.mode_combo.currentData()
        settings["openai_model"] = self.model_combo.currentData()
        settings["quality"] = self.quality_combo.currentData()
        settings["steps"] = str(self.steps_spin.value())
        return settings

    # --- model list -----------------------------------------------------------
    def load_models(self) -> None:
        kind = self.backend_combo.currentData()
        url = self.url_edit.text().strip()
        if kind not in ("a1111", "comfyui"):
            return
        if not url:
            self.set_status("Enter the server address first.", error=True)
            return
        self.load_btn.setEnabled(False)
        self.set_status("Loading models…")
        worker = ModelLoadWorker(kind, url)
        worker.signals.loaded.connect(self.on_models_loaded)
        worker.signals.failed.connect(self.on_models_failed)
        self.pool.start(worker)

    def on_models_loaded(self, models: list) -> None:
        self.load_btn.setEnabled(True)
        current = self.checkpoint_combo.currentText().strip()
        self.checkpoint_combo.clear()
        self.checkpoint_combo.addItems(models)
        if current and current in models:
            self.checkpoint_combo.setCurrentText(current)
        self.set_status(f"Loaded {len(models)} model(s).")

    def on_models_failed(self, message: str) -> None:
        self.load_btn.setEnabled(True)
        self.set_status(message, error=True)

    # --- references -----------------------------------------------------------
    def set_status(self, text: str, *, error: bool = False) -> None:
        self.status_label.setStyleSheet("color: #c0392b;" if error else "color: #555555;")
        self.status_label.setText(text)

    def add_references(self) -> None:
        remaining = ai_char.MAX_REFERENCES - len(self.reference_paths)
        if remaining <= 0:
            self.set_status("You already selected the maximum of 3 photos.", error=True)
            return
        names, _ = QtWidgets.QFileDialog.getOpenFileNames(
            self, "Choose reference photos", "", "Images (*.png *.jpg *.jpeg *.webp);;All files (*)"
        )
        for name in names[:remaining]:
            path = Path(name)
            if path in self.reference_paths:
                continue
            self.reference_paths.append(path)
            item = QtWidgets.QListWidgetItem(QtGui.QIcon(str(path)), path.name)
            item.setData(QtCore.Qt.ItemDataRole.UserRole, str(path))
            self.reference_list.addItem(item)
        if len(names) > remaining:
            self.set_status("Only the first 3 photos were added.")

    def remove_selected(self) -> None:
        for item in self.reference_list.selectedItems():
            path = Path(item.data(QtCore.Qt.ItemDataRole.UserRole))
            if path in self.reference_paths:
                self.reference_paths.remove(path)
            self.reference_list.takeItem(self.reference_list.row(item))

    # --- generate -------------------------------------------------------------
    def generate(self) -> None:
        name = self.name_edit.text().strip()
        try:
            char_id = ai_char.slugify(name)
        except ai_char.AICharError as exc:
            self.set_status(str(exc), error=True)
            return
        settings = self.collect_settings()
        kind = settings["backend"]
        mode = settings["mode"]
        key = self.key_edit.text().strip() or os.getenv("OPENAI_API_KEY", "")

        if mode == "img2img" and not self.reference_paths:
            self.set_status("img2img needs at least one reference photo (or switch to txt2img).", error=True)
            return
        if kind == "openai" and not key:
            self.set_status("Enter an OpenAI API key.", error=True)
            return
        if kind in ("a1111", "comfyui") and not self.url_edit.text().strip():
            self.set_status("Enter the self-hosted server address.", error=True)
            return
        if not self.prompt_edit.toPlainText().strip():
            self.set_status("Enter a prompt.", error=True)
            return
        if char_catalog.find_char(char_id) is not None:
            answer = QtWidgets.QMessageBox.question(
                self, "Replace character?",
                f'A character named "{char_id}" already exists. Replace it with a new generation?',
            )
            if answer != QtWidgets.QMessageBox.StandardButton.Yes:
                return

        if kind == "openai":
            if self.remember_box.isChecked():
                if not secret_store.set_secret(ai_char.SECRET_NAME, key):
                    self.set_status("The keyring could not save the key. Generation will continue.", error=True)
            elif secret_store.get_secret(ai_char.SECRET_NAME):
                secret_store.delete_secret(ai_char.SECRET_NAME)

        ai_backends.save_generation_settings(settings)
        self.generate_btn.setEnabled(False)
        note = " One API request will be charged." if kind == "openai" else ""
        self.set_status("Generating… this can take a bit." + note)
        worker = GenerationWorker(name, list(self.reference_paths), settings, key)
        worker.signals.completed.connect(self.on_completed)
        worker.signals.failed.connect(self.on_failed)
        self.pool.start(worker)

    def on_completed(self, char_id: str, path: str) -> None:
        self.generate_btn.setEnabled(True)
        self.set_status("Saved. Reusing this character does not generate again.")
        self.character_created.emit(char_id)
        self.accept()

    def on_failed(self, message: str) -> None:
        self.generate_btn.setEnabled(True)
        self.set_status(message, error=True)


__all__ = ["AICharDialog", "GenerationWorker", "ModelLoadWorker"]
