name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issue
        if: github.event_name == 'issues'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: yumiaura
          numOfAssignee: 1
      - name: Auto-assign PR
        if: github.event_name == 'pull_request'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          addAssignees: yumiaura
          addReviewers: yumiaura
